package org.omg.PortableServer;


/**
* org/omg/PortableServer/REQUEST_PROCESSING_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/re/workspace/8-2-build-windows-amd64-cygwin/jdk8u101/7261/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Wednesday, June 22, 2016 1:22:40 AM PDT
*/

public interface REQUEST_PROCESSING_POLICY_ID
{

  /**
	 * The value representing REQUEST_PROCESSING_POLICY_ID.
	 */
  public static final int value = (int)(22L);
}
