package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/NON_EXISTENT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Friday, July 25, 2014 8:50:01 AM PDT
*/

public interface NON_EXISTENT
{

  /** Object adapter state indicating that the adapter has been destroyed.
   */
  public static final short value = (short)(4);
}
