package org.omg.PortableServer;


/**
* org/omg/PortableServer/REQUEST_PROCESSING_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableServer/poa.idl
* Friday, July 25, 2014 8:50:00 AM PDT
*/

public interface REQUEST_PROCESSING_POLICY_ID
{

  /**
	 * The value representing REQUEST_PROCESSING_POLICY_ID.
	 */
  public static final int value = (int)(22L);
}
